USE lachica1_Meretas


CREATE TABLE Visitors
(
	VisitorID INT NOT NULL,
	SessionID NVARCHAR(120) NOT NULL,
	CONSTRAINT PK_VisitorID PRIMARY KEY (VisitorID)
)

GO
CREATE TABLE Members 
(
	MemberID INT NOT NULL, 
	MemberEmail NVARCHAR(120) NOT NULL,
	MemberPassword NVARCHAR(120) NOT NULL,
	MemberRole NVARCHAR(60) NOT NULL,
	CONSTRAINT PK_MemberID PRIMARY KEY (MemberID)
)
GO
CREATE TABLE Surveys
(
	SurveyID INT NOT NULL,
	SurveyDescription NVARCHAR(40) NOT NULL,
	CONSTRAINT PK_SurveyID PRIMARY KEY (SurveyID)
)
GO
CREATE TABLE SurveyInstance
(
	VisitorID INT NOT NULL,
	SurveyID INT NOT NULL,
	DateSubmitted DATE NOT NULL,
	TimeSubmitted TIME NOT NULL, 
	CONSTRAINT PK_SurveyInstance PRIMARY KEY (VisitorID, SurveyID),
	CONSTRAINT FK_VisitorID FOREIGN KEY (VisitorID) REFERENCES Visitors(VisitorID),
	CONSTRAINT FK_SurveyID FOREIGN KEY (SurveyID) REFERENCES Surveys(SurveyID)
)
GO


